### ISSUE TITLE
Please create a basic padding class

### ISSUE THREAD

**Issue by brh55** [brh55/HackCSS#2]
Fairly simple, just create a padding class to be used quickly. Should be a reasonable amount of px variation, it's up to you! Implementation is like below:

``` css
/* pad__inside-block-by-(i) */
.pad {
    @for $i from 10 to 50 by 10 {
       @mixin iem inside, block, by-$i {
           padding: $ipx;
     }
}
```

After that's done, run
1. 

```
$ gulp build
```

2.

```
$ git add .
```

3.

```
$ git commit -m "Your message here"
```

4.

```
$ git push
```

5.
Create a PR to this branch when your implementation is done!
